SHELL=bash

#SCRIPTS_DIR=
#PROJECT_NAME=
VERSION=0.0.1

all: ci-build

.PHONY: setup-pipeline
setup-pipeline:

.PHONY: setup
setup:

.PHONY: clean
clean:

.PHONY: build-dev
build-dev:

.PHONY: build
build:

.PHONY: test
test:

.PHONY: publish-dev
publish-dev:

.PHONY: publish
publish:

.PHONY: ci-build-dev
ci-build-dev:

.PHONY: ci-build
ci-build: