PROJECT_NAME=
VERSION=0.0.1

all: ci-build

.PHONY: setup
setup:

.PHONY: clean
clean:

.PHONY: build-dev
build-dev:

.PHONY: build
build:

.PHONY: publish-dev
publish-dev:

.PHONY: publish
publish:

.PHONY: ci-build-dev
ci-build-dev: