trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ${PROJECT_NAME}/*
    - scripts
    - GitVersion.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: TOKENS

steps:
- checkout: self
  clean: true
  lfs: false
  submodules: true
  
- task: UseGitVersion@5
  inputs:
    versionSpec: '5.x'
    useConfigFile: true
    configFilePath: 'GitVersion.yml'

- script: |
    make ci-build -e VERSION=$(GitVersion.SemVer) -e GBESANCON_GITHUB_PACKAGE_TOKEN=$(GBESANCON_GITHUB_PACKAGE_TOKEN)
  workingDirectory: ${PROJECT_NAME}
  displayName: 'CI Build'

- task: CopyFiles@2
  displayName: 'Copy reports'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '${PROJECT_NAME}/build/reports/*-all-reports.zip'
    targetFolder: '$(Build.ArtifactStagingDirectory)/reports'
    flattenFolders: true

- task: CopyFiles@2
  displayName: 'Copy distributions'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '${PROJECT_NAME}/*/build/distributions/?(*.zip|*.tar)'
    targetFolder: '$(Build.ArtifactStagingDirectory)/distributions'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish drop'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop