trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ${PROJECT_NAME}/*
    - scripts
    - GitVersion.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: TOKENS

steps:
- checkout: self
  clean: true
  lfs: false
  submodules: true
  
- task: UseGitVersion@5
  inputs:
    versionSpec: '5.x'
    useConfigFile: true
    configFilePath: 'GitVersion.yml'

- script: |
    make ci-build -e VERSION=$(GitVersion.SemVer) -e GBESANCON_GITHUB_PACKAGE_TOKEN=$(GBESANCON_GITHUB_PACKAGE_TOKEN)
  workingDirectory: ${PROJECT_NAME}
  displayName: 'CI Build'
